- docs/contributing/dev-setup.rst
The dev install instructions are great @yuvipanda and worked nicely!
I just edited two minor things: 
- clarified where/how to run the `install` script (the one before would not be cope & paste-able) 
- fixed the port for the running JupyterHub location, so that the displayed port matches the link itself
> minor fixes to dev-instructions

- bootstrap/bootstrap.py
caches are good! disabling cache should ~only be used when building docker images
> remove —no-cache-dir arg

- tljh/installer.py
We install all python packages from PyPI as much as possible in the
hub environment. A lot of spawners & authenticators do not have conda-forge
packages, but do have pip packages. Keeping all python packages in the
hub environment be installed with pip prevents accidental mixing of python
and conda packages!
> Install all python packages in hub environment with pip

- bootstrap/bootstrap.py
- integration-tests/test_install.py
- tljh/installer.py
- tljh/systemd-units/configurable-http-proxy.service
- tljh/systemd-units/jupyterhub.service
This pulls out most of #51, minus the acl+setgid complexity
- move proxy secret to state dir (closes #44)
- move state dir outside env
- test permissions of various files and directories
- fix some weird permissions found by the tests
This includes the permissions tests from #51 for admin-install permissions, but they are disabled as xfail, since we don't have the feature yet.
> move state outside envs

- bootstrap/bootstrap.py
use >= instead of == to check installed version
pulled out of #51
> bootstrap: allow conda to be upgraded

- docs/howto/resource-estimation.rst
- docs/index.rst
- docs/tutorials/digitalocean.rst
- docs/tutorials/google.rst
- docs/tutorials/jetstream.rst
> Add a how-to guide on selecting VM Memory / CPU / Disk size

- .circleci/config.yml
- bootstrap/bootstrap.py
- tests/test_conda.py
- tests/test_installer.py
- tljh/apt.py
- tljh/conda.py
- tljh/installer.py
- tljh/systemd-units/configurable-http-proxy.service
- TLJH should support raspberry pi, which runs ARM. conda does
not support ARM.
- Get nodejs from nodesource instead of conda or default repositories.
Default repositories get out of date pretty quickly.
- Install CHP from npm
Refer #62
> Use venv for base hub environment

- .circleci/config.yml
- Can cache entire venv directory. When installing with system
pip3, /usr/local/bin/ also needs caching - maybe other
places too!
- Matches how the installer does things more closely
This should fix broken tests
> Use a venv to run unit tests

- MANIFEST.in
- docs/howto/https.rst
- docs/index.rst
- setup.py
- tljh/config.py
- tljh/configurer.py
- tljh/installer.py
- tljh/jupyterhub_config.py
- tljh/systemd-units/configurable-http-proxy.service
- tljh/systemd-units/traefik.service
- tljh/traefik.py
- tljh/traefik.toml.tpl
Not this PR:
- read traefik.toml
- read/write acme.json
- listen on 80/443
- nothing else
Config for letsencrypt (not tested yet):
```yaml
https:
enabled: true
letsencrypt:
email: "you@email.com"
domains:
- myhost.horse
```
and for manual tls:
```yaml
https:
enabled: true
tls:
cert: /path/to/my.cert
key: /path/to/my.key
```
> Add HTTPS support with traefik

- tljh/config.py
- tljh/configurer.py
- tljh/installer.py
- tljh/jupyterhub_config.py
Simply reloading traefik is not enough - we need to actually
write the new traefik.toml file.
> Fix traefik config reload

- tests/test_config.py
- tljh/config.py
- add remove-item to cli
- fix setting non-string values (int, bool, float)
- show help when no action is given
- test coverage for cli
> tests and fixes in tljh-config

- docs/PULL_REQUEST_TEMPLATE.md
- docs/contributing/code-review.rst
- docs/contributing/docs.rst
- docs/index.rst
Also add a pull request template
> Document code-review practices

- .circleci/config.yml
codecov upload has been failing since #72. I think because `coverage` is not installed on $PATH. <del>Activating the env should fix it, but will wait for CI to confirm.</del> It works. Had to use a bizarre `echo export >> $BASH_ENV ` snippet because [circleci doesn't support setting standard environment variables](https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables).
> fix coverage uploads

- docs/index.rst
- docs/topic/customizing-installer.rst
- docs/topic/installer-actions.rst
- docs/tutorials/custom.rst
- docs/tutorials/digitalocean.rst
- docs/tutorials/google.rst
- docs/tutorials/jetstream.rst
- integration-tests/Dockerfile
- integration-tests/test_hub.py
- integration-tests/test_install.py
- tljh/installer.py
This lets `sudo -E` work when calling tljh-config. It currently
does not, since we do not add the hub venv to PATH
> Symlink tljh-config to /usr/local/bin

- docs/index.rst
- docs/topic/escape-hatch.rst
- tljh/jupyterhub_config.py
We want to keep the amount of custom code we support extremely
small. This provides a nice escape hatch for everything else.
> Load arbitrary .py config files from a conf.d dir

- dev-requirements.txt
- tests/conftest.py
- tests/test_config.py
- tests/test_traefik.py
- tljh/traefik.py
This isn't the integration tests requested in #92, but it gets coverage for traefik.py. In particular, this validates that we are creating valid toml, but in no way validates that it tells traefik to do what we want it to.
includes #95
> unittests for traefik

- docs/howto/share-data.rst
- docs/index.rst
- docs/install/custom.rst
- docs/install/digitalocean.rst
- docs/install/google.rst
- docs/install/jetstream.rst
This is some wording to show people how to distribute data with their users. Let me know what you think!
closes #101 
closes #102 (by a rebase accident? idk!)
> shared data and username emphasis

- docs/conf.py
- docs/doc-requirements.txt
- tljh/config.py
This PR does two things:
* adds the sphinx copybutton to the code blocks
* fixes the bug that was causing integration tests to fail.
* For some reason the result of loading the yaml was no longer an instance of `dict` but instead was an instance of `CommentedMap`. That was causing [this line](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/config.py#L53) to always return True, which was creating an empty dictionary and removing any previous values in that final node. This PR checks for that type as well and it's now passing tests.
closes #122
> adding copy button to code blocks and fixing the integration bug

- docs/index.rst
- docs/topic/whentouse.rst
This adds a page to try disambiguating when to use TLJH vs. Z2JH. It partially addresses #75 .
I'm sure that I got some points wrong or didn't explain them well. Feel free to push directly to the branch or make suggestions!
> adding when to use tljh page

- .circleci/config.yml
- .circleci/integration-test.py
- docs/contributing/code-review.rst
- docs/contributing/tests.rst
- docs/index.rst
- integration-tests/test_hub.py
Provide higher level run-test command in integration-tests.
This runs a number of pytest files in the same container
with the same installation.
Fixes #97
> Make it easier to run multiple independent integration tests

- .circleci/config.yml
- docs/conf.py
- docs/environment.yml
- docs/requirements.txt
> Switch back to a venv for docs + fix .circle config

- readthedocs.yml
Fixes build for now, hopefully. Venv is configured via
the web interface
> Remove readthedocs.yml file

- .circleci/config.yml
- .circleci/integration-test.py
- docs/contributing/plugins.rst
- docs/index.rst
- docs/topic/customizing-installer.rst
- integration-tests/plugins/simplest/setup.py
- integration-tests/plugins/simplest/tljh_simplest.py
- integration-tests/test_simplest_plugin.py
- setup.py
- tljh/hooks.py
- tljh/installer.py
TLJH is a great base to build 'stacks' on top of
for various use cases. These 'stacks' should be built by
people who are domain experts in their fields, and easily
updateable with new TLJH versions. Extension points need
to be very clearly defined & evolvable, so we can modify
TLJH without fear of breaking everything.
[pluggy](https://pluggy.readthedocs.io/) is the plugin
mechanism for pytest spun out into its own library,
and fits our requirements well.
There is an experimental pangeo stack in progress at
https://github.com/yuvipanda/tljh-pangeo for an example
of how this would work
> Add plugin support to the installer

- docs/howto/admin/admin-users.rst
- docs/howto/admin/https.rst
- docs/howto/auth/dummy.rst
- docs/howto/auth/firstuse.rst
- docs/howto/auth/github.rst
- docs/howto/content/add-data.rst
- docs/howto/content/share-data.rst
- docs/howto/env/notebook-interfaces.rst
- docs/topic/authenticator-configuration.rst
- docs/topic/installer-actions.rst
- docs/topic/tljh-config.rst
- integration-tests/test_hub.py
- integration-tests/test_install.py
- tljh/installer.py
Removes a lot of 'sudo -E' usage, and eventually should
let us get rid of the $PATH override for jupyterhub-admins,
which arguably is less secure than just dropping stuff into
/usr/bin
> Move tljh-config symlink to /usr/bin

- tljh/installer.py
JupyterLab currently doesn't let you install extensions
with node 10, so move back to 8
> Use node 8, not 10

- docs/conf.py
The API for sphinx-copybutton changed slightly again (hopefully for the last time). This fixes that
> Copybutton fix

- tljh/conda.py
conda's stderr is *not* guaranteed to be JSON when you are
passing --json. We let it bleed through for now. In the
longer term, we should capture this separately.
Ref #148, which I think is caused by this (along with conda
releasing a newer version than what we have
> Don't capture stderr when calling conda

- README.rst
- docs/howto/admin/resource-estimation.rst
- docs/howto/env/user-environment.rst
- integration-tests/plugins/simplest/tljh_simplest.py
- tljh/config.py
- tljh/systemd.py
Using `codespell -q3 -w` that I just discovered.
(https://github.com/codespell-project/codespell, pip install codespell)
And fixing one manually.
> Fix some typos

- .circleci/integration-test.py
and missing start-container command
integration-test was refactored a bit, and some of the commands not used on circleci stopped working
Having these helps for local testing
> missing arguments in integration test commands

- tljh/installer.py
removed formatting  symbol f'', since "....x" is considered as a type in the formatting.
actual directory  is just "https://github.com/nodesource/distributions/blob/master/deb/setup_8.x"
> installer.py: remove unused f"..."

- integration-tests/conftest.py
- integration-tests/test_proxy.py
adds integration test for manual https certs
closes #92
> test manual https setup

- tljh/installer.py
- tljh/jupyterhub_config.py
fixes TERM shutdown
bumps oauthenticator to 0.8 as well
> jupyterhub 0.9.2

- docs/topic/security.rst
- tests/test_user.py
- tljh/user.py
World-Readable seem to be a surprising default for many people,
especially in teaching context. Switch to a more reasonable `rwxr-x---`
We have to issue a chmod, as changing at creation time would require
changin /etc/adduser.conf DIR_MODE=0760 (or whatever), but that seem
unwise.
We do not set the exact permission in case the DIR_MODE is more
restrictive.
Closing #158
(cc @mstobb)
One question is do we want that to be configurable ? I tend to think no.
> Don't create home publicly readable

- docs/contributing/dev-setup.rst
- docs/howto/env/notebook-interfaces.rst
- docs/topic/escape-hatch.rst
- integration-tests/test_simplest_plugin.py
- tests/conftest.py
- tests/test_installer.py
- tests/test_migrator.py
- tljh/config.py
- tljh/installer.py
- tljh/jupyterhub_config.py
- tljh/log.py
- tljh/migrator.py
easier to maintain proper private permissions and consolidate, since we have multiple config files (config.yaml, jupyterhub_config.d)
I thought there was an issue about this, but I can't seem to find it right now.
> put config in `$tljh/config` directory

- docs/topic/customizing-installer.rst
Looks like [pypi.org](https://pypi.org) was intended :)
> Fix minor typo: pypy -> pypi

- docs/topic/tljh-config.rst
- tests/test_configurer.py
- tljh/configurer.py
This is a continuation of #153
> No memory limit (continued)

- tljh/config.py
There used to be two separate errors that occurred if we run the command without sudo:
[Errno 13] Permission denied: '/opt/tljh/installer.log'
at line 226
And 
[Errno 13] Permission denied: '/opt/tljh/config/config.yaml'
at lines 294-305
Now we print an error and print a message about using 'sudo -E'.
I thought about putting the whole main function into one try-except block, but it seems more appropriate to use two different try-except blocks.
https://github.com/jupyterhub/outreachy/issues/5
closes #120
> add warning if tljh-config is called as non-root user

- docs/contributing/packages.rst
- docs/index.rst
- integration-tests/test_extensions.py
- tljh/installer.py
Upgrades following packages:
- JupyterHub
- JupyterLab
- Notebook
- nteract
Fixes #214
> Upgrade package versions

- tests/test_yaml.py
- tljh/config.py
- tljh/installer.py
- tljh/yaml.py
workaround ruamel.yaml issue https://bitbucket.org/ruamel/yaml/issues/255, where once an empty dict or list has been written, 'flow' style is used thereafter, using dense `{key: value}` form instead of traditional yaml block style.
> consolidate yaml configuration

- .circleci/config.yml
- bootstrap/bootstrap.py
- docs/index.rst
- integration-tests/conftest.py
- integration-tests/test_bootstrap.py
- integration-tests/test_distro.py
> Provide better error message when running on unsupported distro

- docs/index.rst
- docs/install/custom-server.rst
- docs/troubleshooting/providers/custom.rst
Most people won't need to do this, so let's move it
to the troubleshooting page
> Move custom server troubleshooting code to its own page

- tljh/installer.py
This uses v0.12 which allow for deleting users before they have set their password.
Is any of the above necessary?
> Use newer firstuseauthenticator

- integration-tests/test_hub.py
We'll need to figure out why this is failing
> Mark flaky test as flaky

- docs/howto/admin/enable-extensions.rst
--system installs stuff into /etc, and should practically never
be used alongside conda / virtualenv.
> Use --sys-prefix for installing nbextensions

- tljh/installer.py
See #290.  Users reported Kernel connection issues with tornado >= v6.  Let's see if this fixes it.
> Pin tornado to <6

- docs/howto/auth/nativeauth.rst
Moved the config to a code block because as rendered, the commands blend and create an error when trying to c&p. Also removed the 1. because there's no 2. Here's as currently rendered in docs:
And here's the change:
- [ x ] Add / update documentation
> DOC: moved nativeauthentic config instructions to code block

- tljh/installer.py
This takes TLJH to notebook 5.7.8. According to PyPI 5.7.7 was never released so I think this fixes typo.
> [MRG] Fix the version tag of the notebook package

- docs/_static/custom.css
- docs/conf.py
- docs/index.rst
This does a couple things:
1. Adds sidebar links for the table of contents, so you can navigate to other pages from within sub-pages
2. Adds captions to the toctrees, so that there are headers in the sidebar links
3. Adds css to make the within-page captions invisible because we're already using headers for this instead of captions
curious what @yuvipanda or @leportella think about this!
> adding sidebar links

- README.rst
Fixed the link for AWS docs to point to the right location.
> Update Readme for the AWS docs link

- docs/index.rst
Aug '18 has come and gone, and people have been using
TLJH to great effect for a while. Reflect that in 'development
status'
> Remove ominous warning with outdated release date

- docs/howto/admin/resize.rst
- docs/howto/providers/digitalocean.rst
- docs/index.rst
- docs/install/digitalocean.rst
Since you usually don't want to resize right after you
create a VM, I've moved it to a more central 'cloud provider
tasks' page. We can add additional things here too. It
matches similar provider specific pages we have for
troubleshooting
> Move digital ocean 'resize' docs out of 'install' step

- tests/test_configurer.py
- tljh/configurer.py
mem_limit & cpu_limit are traitlets on the parent
Spawner class. Setting these here allows plugins to
do the dangerous job of swapping the SystemdSpawner
out for something else
> Use c.Spawner to set mem_limit & cpu_limit

- bootstrap/bootstrap.py
- integration-tests/test_bootstrap.py
- Check for Python Version
- Check if systemd is present
- Provide more useful error message when running inside
an unprepared docker container
Ref #16
> Add more validation to bootstrap.py

- docs/contributing/dev-setup.rst
- docs/install/custom-server.rst
> Add note about not running on your own laptop or in Docker

- .circleci/integration-test.py
- docs/howto/admin/resource-estimation.rst
- docs/install/amazon.rst
- docs/install/custom-server.rst
- docs/install/google.rst
- docs/install/jetstream.rst
- Run all integration tests with a 768MB memory limit,
so we know when we're using too much RAM
- Document this memory requirement in our docs.
Fixes #257
> Limit memory available in integration tests

- setup.py
- tljh/conda.py
- tljh/installer.py
- tljh/traefik.py
As discussed in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/277:
> Upgrade while https enabled

- docs/topic/tljh-config.rst
- tests/test_config.py
- tljh/config.py
closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/203
I added the option to unset (remove) a config property. @yuvipanda, I'm not sure if this is wanted but I thought it would be nice to be able to remove a config property the same way we're setting it, without editing the config file.
> Add "tljh-config unset" option

- docs/howto/admin/https.rst
- docs/troubleshooting/logs.rst
- Wrap some lines
- Normalize reference anchors to conform to hierarchy
- Mention that the certificates will be renewed
- Strengthen suggestion to use Let's Encrypt
- Note that Let's Encrypt doesn't work in internal
networks not accessible from the internet
- Note that you need a domain name before you can
set up HTTPS
- Add section on troubleshooting HTTPS
- Add section on getting traefik logs, and remove section
on configurable-http-proxy (which we no longer use)
Fixes #305
Fixes #217
> Cleanup HTTPS documentation

- bootstrap/bootstrap.py
This change is required, to support Ubuntu Server 18.04.01, which by default doesn't ship with universe. Universe contains python3-venv which is needed for tljh
> Adds the universe repository to the used sources

- docs/topic/tljh-config.rst
Fixed the problem docs for tljh-config incorrectly listing the location of the config.yaml file (Issue #354).
> Fixed out of date config directory listed in docs for tljh-config

- tljh/installer.py
- tljh/systemd-units/jupyterhub.service
bump oauthenticator patch as well
> Upgrade to JupyterHub 1.0

- tljh/installer.py
closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/356
> Suppress insecure HTTPS warning when upgrading TLJH

- bootstrap/bootstrap.py
- dev-requirements.txt
- integration-tests/test_install.py
- tests/test_utils.py
- tljh/apt.py
- tljh/conda.py
- tljh/installer.py
- tljh/utils.py
- When processes fail, they actually print a failure message
on the user's terminal
- Regardless of success or failure, we print all output to
/opt/tljh/installer.log
- Make sure installer.log isn't readable by non-root users
This should make debugging people's issues *much* easier, since
we can actually see the output of failing commands rather than
having to guess.
Fixes #84 
Fixes #142
> Provide much better error messages

- README.rst
- docs/howto/providers/azure.rst
- docs/index.rst
- Change title of azure config howto
- Link to azure docs from README
- Keep all the cloud provider links together in the
documentation index
> Minor azure doc cleanup

- tljh/installer.py
It's generally more bugfree and performant.
We install dependencies of pycurl, including build-essential.
build-essential is used by many other dependencies
as well - particularly psutil for nbresuse.
Fixes #289
Fixes #286
> Install & use pycurl for requests

- docs/topic/authenticator-configuration.rst
- tljh/installer.py
Is popular enough we should let people use it by
default
> Add tmpauthenticator by default to TLJH

- docs/topic/authenticator-configuration.rst
- integration-tests/plugins/simplest/tljh_simplest.py
- integration-tests/test_simplest_plugin.py
- tljh/hooks.py
- tljh/installer.py
- tljh/jupyterhub_config.py
- Add hook for installing additional hub packages
- Add hook for additional `jupyterhub_config.py`
entries
> Add custom hub package & config hooks

- README.rst
This PR fixes the typesetting of the Azure link in the README. 
Before:
After:
> Fix typo in README link

- docs/install/ovh.rst
> Fix typo: missing "c" for instance

- docs/index.rst
- docs/topic/idle-culler.rst
- integration-tests/test_hub.py
- tests/test_configurer.py
- tljh/configurer.py
- tljh/cull_idle_servers.py
- tljh/jupyterhub_config.py
@yuvipanda, I decided to give this a try :D
However, I have some questions and doubts.
Is there a better way to access the *cull_idle_servers.py*, without actually copying it to TLJ?
I'm not sure about the test either... Is it ok for the it to be part of *test_hub.py* since the idle culler is managed by JupyterHub?  Also, I'm not sure I'm testing correctly that the user's server was culled.
> Add idle culler

- README.rst
- docs/topic/security.rst
According to 3af53522, TLJH is in beta state by now. This commit
replaces the other occurrences in the documentation to make it
consistent. Also syncs other paragraphs from index.rst to README.rst,
see 5374f5ea.
> Replace pre-alpha by beta state in documentation

- tests/test_configurer.py
- tljh/configurer.py
Regarding https://github.com/jupyterhub/the-littlest-jupyterhub/issues/384, this PR removes the hard-coded path of the idle culler and runs the script as a python module.
> Run idle culler as a python module

- docs/contributing/plugins.rst
Fix the rendering of the link to the plugins hooks in the documentation.
> Fix link to the hooks in plugins docs

- integration-tests/plugins/simplest/tljh_simplest.py
- integration-tests/test_simplest_plugin.py
- tljh/hooks.py
- tljh/installer.py
Add a new `tljh_post_install` hook to allow the execution of arbitrary post install actions.
> Add tljh_post_install hook

- docs/topic/tljh-config.rst
- integration-tests/test_hub.py
- tests/test_configurer.py
- tljh/configurer.py
- tljh/jupyterhub_config.py
@yuvipanda, I added support to add a user to a specific group, but I'm not sure if *UserCreatingSpawner* is the perfect place to do it.
What do you think?
closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/349
> Allow adding users to specific groups

- docs/howto/auth/github.rst
- docs/topic/tljh-config.rst
Related to https://github.com/jupyterhub/the-littlest-jupyterhub/issues/402, it think we should make it clear that if the http/https ports are changed, the proxy should be reloaded.
> Docs update: reload proxy after modifying the ports

- tests/test_installer.py
- tljh/installer.py
Added the *append* action to the *--admin* option.
> Allow adding multiple admins during install 

- tests/test_conda.py
The tests are failing for some time :( However, the strange thing is that the tests in *test_conda.py* all pass if ran individually. 
At first I thought this might be related to the newer version of pytest (since the tests passed if each of it got its own instance of the `prefix` fixture). But there wasn't any pytest change to justify the behavior.
After more digging, the issue I noticed is that after the first ``conda.ensure_conda_packages`` call, the environment got modified and instead of having symlinks to python3.6, there were instead to python3.7, hence the "ModuleNotFoundError: No module named 'conda'" error.
<details>
<summary>conda-meta/history  contents before the running any test</summary>
```
+defaults::python-3.6.5-hc3d631a_2
+defaults::ca-certificates-2018.03.07-0 …
```
> Fix failing conda tests

- tljh/systemd-units/jupyterhub.service
- tljh/systemd-units/traefik.service
This disables ProtectHome for jupyterhub process and enables it for the traefik process (ref: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/431).
Should fix https://github.com/jupyterhub/the-littlest-jupyterhub/issues/431, https://github.com/jupyterhub/the-littlest-jupyterhub/issues/408 and https://github.com/jupyterhub/the-littlest-jupyterhub/issues/237.
> Disable ProtectHome=tmpfs

- docs/install/custom-server.rst
Fixes installation failure on clean box, which received this error during installation:
In file included from src/docstrings.c:4:0:
src/pycurl.h:4:10: fatal error: Python.h: No such file or directory
#include <Python.h>
^~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> installation failed due to no python3-dev packages

- tljh/installer.py
* Upgrade **firsuseauthenticator** to v0.13.0 to include [a fix](https://github.com/jupyterhub/firstuseauthenticator/pull/23) that solves the *500 : Internal Server Error* when accessing  `/hub/auth/change-password`.
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/306
* Upgrade **oauthenticator** to v0.10.0 to offer support for aws cognito.
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/471
> Upgrade authenticators

- .circleci/integration-test.py
- docs/howto/admin/resource-estimation.rst
- docs/install/amazon.rst
- docs/install/custom-server.rst
- docs/install/google.rst
- docs/install/jetstream.rst
- integration-tests/plugins/simplest/tljh_simplest.py
- integration-tests/test_simplest_plugin.py
Apparently the 768MB memory limit is not enough anymore and it caused the integration tests failure.
Increasing it to 1GB seems to solve the issues (at least for now).
ref: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/257 and https://github.com/jupyterhub/the-littlest-jupyterhub/pull/335
P.S: Remaining things to do for the tests to pass: find out why the test in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/453 fails.
> Fix failing integration tests

- docs/topic/requirements.rst
The link was missing the `admin` folder under `howto`.
> Fix broken link to resource estimation page

- integration-tests/test_install.py
This is an attempt to fix the integration test. Closes #490.
The TL;DR is that the [newest version of pip](https://pip.pypa.io/en/stable/news/#features) will switch to the behaviour of `pip install --user ...` when you run `pip install ...` without being able to write to the global package directory. This means our integration test started to fail because the install we were doing now succeeded. However we were testing if a user could install things to the global directory or not. This means the test failing was a false positive (the install succeeded but not because the user could write to the global dir).
This PR makes it so that the `pip` command used in the test won't enable `--user` if it can't write to the global directory. Instead it will fail (as it used to).
An alternative would …
> [MRG] Fix integration test for new pip

- CONTRIBUTING.rst
- README.rst
- docs/contributing/index.rst
This PR links the contributing guide more prominently.
i also changed the wording at the top of the contributing section a bit. This is taken from what we have in https://repo2docker.readthedocs.io/en/latest/contributing/contributing.html. For BinderHub we have a slightly different setup https://github.com/jupyterhub/binderhub#contributing
I think making it as easy as possible to find the contributing guide helps show people new to the project that there are several ways of contributing and that they aren't super difficult or require specialised knowledge. It is also useful for repeat contributors because they want a reminder of how things work (build the docs, run the tests, etc).
What do you think?
> [MRG] Link contributing guide

- .circleci/config.yml
- docs/contributing/dev-setup.rst
- docs/howto/admin/admin-users.rst
- docs/topic/customizing-installer.rst
- integration-tests/test_admin_installer.py
- setup.py
- tests/test_installer.py
- tljh/installer.py
Added the option to set the admin user password during install (closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/263).
If the installer is called with *--password* option, then a password will be requested for each admin user specified with *--admin**. If *--password* is not present, the script will behave like before.
@yuvipanda, can you please give me some advice about how/if should I test this? :eyes:
> Set admin password during install

- bootstrap/bootstrap.py
- docs/howto/env/user-environment.rst
- docs/install/index.rst
- tests/test_conda.py
- tljh/installer.py
This PR follows the steps in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/250#issuecomment-511085121 to use Python3.7 with fresh TLJH installs, but doesn't upgrade the Python version for existing installs.
> Make Python3.7 the default

- tests/test_traefik.py
- tljh/traefik.toml.tpl
This sets TLS 1.2 to be the minimum tls version for the https entry point.
traefik 1.7 docs ref: https://docs.traefik.io/v1.7/configuration/entrypoints/#specify-minimum-tls-version
closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/488
> Set tls 1.2 to be the min version

- integration-tests/test_extensions.py
- tljh/installer.py
This PR upgrades Jupyterlab to the latest version of 1.2.6 as of Feb 1st 2020. Build and integration tests passes locally. 
- `jupyterlab-hubextension` removed because this has been integrated to Jupyterlab 1.0.0+ 
- Added `--minimize=False` option to Jupyterlab installation to avoid flaky build on low resource CI pipelines
> Upgrade jupyterlab to 1.2.6

- integration-tests/test_extensions.py
- tljh/installer.py
- tljh/requirements-base.txt
requirements file is easier to work with and update than inlined strings
In the future, we should be doing `pip freeze` and using the frozen result, like we do (with conda) in repo2docker because pinning only direct dependencies is a way to guarantee broken environments in the future (see the pinning-down of tornado as one example).
Several dependencies are updated in the process (jupyterlab 1.1, notebook 6.0, etc.)
> switch base environment to requirements file

- MANIFEST.in
Include `requirements-base.txt` in MANIFEST so it gets installed.
Fixes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/502
> Fix missing reference to requirements-base.txt

- tljh/installer.py
There is a bug in the upgrade logic of the installer. On a fresh TLJH install, conda 4.8.1 is installed.
If the installer is run again, instead of using the existing conda 4.8.1, conda 4.5.8 is installed and used, producing a *CondaUpgradeError*. 
This should fix this issue.
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/517 
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/332
> Fix installer

- .circleci/config.yml
1. When implementing https://github.com/jupyterhub/the-littlest-jupyterhub/pull/511, I didn't realize that when a TLJH fork doesn't have CircleCI setup there's no CIRCLE_PROJECT_USERNAME env var. Instead there is a  CIRCLE_PR_USERNAME that can be used.
Example:
* My TLJH fork has CircleCI setup, there are these env vars available:
* @minrk and @jtpio recent PRs don't have these env vars and instead have:
2. Another way to solve this issue is installing from git refs (available since [pip 10](https://pip.pypa.io/en/stable/news/#id280)). However this would imply some gymnastics parsing the CIRCLE_PULL_REQUEST var.
like this:
```
index = CIRCLE_PULL_REQUEST.find("/pull/")
BOOTSTRAP_PIP_SPEC="git+" + CIRCLE_PULL_REQUEST[:index] + ".git@ref" + CIRCLE_PULL_REQUEST[index:] + "/head"
```
So that …
> Use PR username when no CircleCI project

- tljh/installer.py
Minor typo fix: enviornment -> environment
> Fix typo in --user-requirements-txt-url help

- docs/conf.py
- docs/requirements.txt
The `pydata-sphinx-theme` is now available on PyPI and conda-forge.
See also: https://github.com/jupyter/repo2docker/pull/864 and https://github.com/jupyterhub/the-littlest-jupyterhub/pull/537#pullrequestreview-379476596.
> Update the docs theme to pydata-sphinx-theme

- docs/howto/content/add-data.rst
Fix a minor formatting issue in the how-to guides.
> Fix code block formatting in the docs

- docs/topic/installer-actions.rst
This adds to the docs instructions on how to get rid of what the TLJH installer adds to the system (as per [@yuvipanda's suggestion](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/128#issuecomment-438421341)).
Hope I covered everything :eyes: .
Relevant issue: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/128
> Provide instructions on how to revert each action of the installer

- docs/contributing/plugins.rst
Fixes #550.
This change adds a section about known TLJH plugins to the documentation:
> Add a section about known TLJH plugins to the documentation

- .circleci/config.yml
- bootstrap/bootstrap.py
- dev-requirements.txt
The unit test were failing because of the latest grpcio version 1.28.0, that switches to manylinux2010 (see [this announcement](https://groups.google.com/forum/#!msg/grpc-io/VdoTPMT5WwU/fMmXxFiBAwAJ) for details) (`grpcio` is a requirement of the `etcd3` python client used by traefik-proxy).
I tried a clean install of TLJH on DO and everything went ok, so referring to the info in the announcement I guess it has something to do with the Ubuntu Docker image and the libs there.
> Fix failing unit test

- .circleci/config.yml
- .circleci/integration-test.py
This makes `bootstrap_pip_spec` an optional argument so that when running the integration tests locally, users won't need to add the empty string as an arg (for the default tljh bootsrap pip spec) or the entire pip spec.
-~[ ] Add / update documentation~
-~[ ] Add tests~
> Make bootstrap_pip_spec test argument optional

- docs/contributing/tests.rst
Update the docs to run the integration tests locally.
The `bootstrap_pip_spec` parameter can be specified before the test files to avoid shifting the arguments, similar to the Circle CI script:
https://github.com/jupyterhub/the-littlest-jupyterhub/blob/01ba34857dd4e316d839034ae2b3cc400b929964/.circleci/config.yml#L59-L61
> Add bootstrap pip spec to the integration test docs

- .circleci/config.yml
- .circleci/integration-test.py
- docs/contributing/tests.rst
Quick follow-up for https://github.com/jupyterhub/the-littlest-jupyterhub/pull/558 and https://github.com/jupyterhub/the-littlest-jupyterhub/pull/563, to keep the style consistent with other parameters such as `--installer-args`.
> Rename to --bootstrap-pip-spec in the integration tests

- docs/contributing/plugins.rst
Add [tljh-repo2docker](https://github.com/plasmabio/tljh-repo2docker) to the list of known plugins.
This plugin can be used to build multiple user environments with `repo2docker`.
> Add tljh-repo2docker to the list of plugins

- docs/contributing/dev-setup.rst
- docs/howto/admin/admin-users.rst
Added a link to the repo in the docs at a useful point.
> Add a useful link to the git repo, fix a typo, in docs

- tljh/installer.py
In the [`run_plugin_actions`](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/01ba34857dd4e316d839034ae2b3cc400b929964/tljh/installer.py#L399) function, hooks are retrieved from the `plugin_manager`, and the `plugins` argument doesn't seem to be used.
This change removes the unused `plugins` argument.
> Remove unused plugins argument from run_plugin_actions

- .circleci/integration-test.py
- docs/howto/admin/resource-estimation.rst
- docs/install/amazon.rst
- docs/install/custom-server.rst
- docs/install/google.rst
- docs/install/jetstream.rst
The integration tests are failing again :confused:  
This time it has to do with conda and not with the JupyterLab build. Also, it doesn't look to be intermittent anymore.
The error is:
```
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'conda', 'install', '-c', 'conda-forge', '--json', '--prefix', '/opt/tljh/user', 'conda==4.8.1']' died with <Signals.SIGKILL: 9>.
```
Update: Looks like increasing the mem from 1G to 1.15G is enough (at least for now)
> Provide more memory for integration tests

- tests/test_conda.py
- tljh/conda.py
- tljh/installer.py
miniconda downloader now provides sha256 hashes. Previously
it provided only md5 hashes. md5 is deprecated everywhere for
everything, so let's use this
> Use sha256 sums for verifying miniconda download

- .circleci/config.yml
- dev-requirements.txt
- docs/topic/escape-hatch.rst
- integration-tests/test_proxy.py
- tests/conftest.py
- tests/test_traefik.py
- tljh/traefik.py
This allows extending traefik's config by adding `*.toml` snippets of traefik config in `traefik_config.d` directory. This is similar with how unsupported JupyterHub config is plugged into TLJH.
Unfortunately, since Traefik < 2.0 doesn't allow `yaml` configs I had to stick to `toml`. 
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/543
> Allow extending traefik config

- tljh/config.py
Use `http://127.0.0.1:80/hub/api` to check for hub ready. The response for the the `/hub/api` endpoint is as follows:
```json
{"version": "1.1.0"}
```
The main motivation for this change is the use of the `LTIAuthenticator` which returns a 405 after it has been configured as mentioned in https://github.com/jupyterhub/ltiauthenticator#edx (step 5).
> Use /hub/api endpoint to check for hub ready

- .circleci/integration-test.py
- docs/howto/auth/awscognito.rst
- docs/install/amazon.rst
- docs/install/azure.rst
- docs/install/custom-server.rst
- docs/install/digitalocean.rst
- docs/install/google.rst
- docs/install/jetstream.rst
- docs/install/ovh.rst
- docs/topic/customizing-installer.rst
- Shorter URL makes the horizontal scrollbar in the TLJH
docs site much better!
- Shorter URLs are cooler
- This redirect is managed by readthedocs, with the interface
available at https://readthedocs.org/dashboard/the-littlest-jupyterhub/redirects/
> Use tljh.jupyter.org/bootstrap.py to get installer

- .circleci/integration-test.py
- docs/howto/auth/awscognito.rst
- docs/install/amazon.rst
- docs/install/azure.rst
- docs/install/custom-server.rst
- docs/install/digitalocean.rst
- docs/install/google.rst
- docs/install/jetstream.rst
- docs/install/ovh.rst
- docs/topic/customizing-installer.rst
> add -L option to curl to follow redirect

- docs/contributing/dev-setup.rst
Update documentation. I actually submitted this as a PR a couple of weeks ago, but managed to get it wrong, sorry!
I gave you a markdown link but it should have been rst...
This time I even ran the doc build and tests...
> Fixed git repo link from markdown to rst

- .circleci/config.yml
Now that we have enabled RTD PR build, we don't need to build our docs with CircleCI
> Remove CircleCi docs build

- tljh/config.py
This patch loads the configuration to specify http port while checking the hub, to fix the issue #588 
On check_hub_ready
> Use http port from config while checking hub

- docs/topic/idle-culler.rst
> Add link to jupyterhub-idle-culler

- docs/conf.py
- docs/howto/index.rst
The RTD build was failing with [``TemplateNotFound('about.html') error``.](https://readthedocs.org/projects/the-littlest-jupyterhub/builds/12133621/) I believe this was because, before `pydata-sphix-theme v.0.4.1`, there was no `html_sidebars` feature (thanks @choldgraf  for adding it :partying_face:), so it was not complaining that we were still using the sidebars from the old one. Removing the old sidebars and using the ones from the new theme, seams to be fixing the issue.
(This also fixes the left TOC for the `how-to` docs section)
> Fix doc build

- docs/conf.py
The docs are looking funny because of my last PR https://github.com/jupyterhub/the-littlest-jupyterhub/pull/624 :confused: .
The `pydata-sphinx-theme` sidebars are enabled by default, there's no need to list them. Having these together with the sphinx `html_sidebars`  builtins, make the docs look funny, like in the screenshot above. So, I believe it is best to stick with the theme's defaults.
> Fix html_sidebars

- .circleci/integration-test.py
- docs/howto/admin/resource-estimation.rst
- docs/install/amazon.rst
- docs/install/custom-server.rst
- docs/install/google.rst
- docs/install/jetstream.rst
Tests are failing *again* probably because of not enough memory. We've had this issue before :confused: 
This bumps the mem to 1.5G. Hope it'll be enough
> Bump memory again for integration tests

- bootstrap/bootstrap.py
- docs/topic/tljh-config.rst
- integration-tests/test_hub.py
- tests/test_configurer.py
- tljh/config.py
- tljh/configurer.py
This pull request:
* fixes #616 
* fixes #216
* fixes #426
A function update_base_url now sets c.JupyterHub.base_url to the requested value, and correctly checks for it during the check_hub_ready function.
> Add base_url capability to tljh-config

- docs/howto/auth/firstuse.rst
I had to do this additional step to allow the user to log-in again.
(I did not build the docs and I am not a rst person, but I think the change should be valid rst.)
> Add a necessary step to reset password

- docs/howto/auth/firstuse.rst
Doc of how users can change password for First Use Authenticator.
> Doc of how users can change password

- integration-tests/test_proxy.py
- tljh/installer.py
* Pin `chardet` in the hub environment to a version that doesn't conflict with traefik-proxy's `aiohttp` requirement until we figure out what is going on.
* Bump the `jupyterhub` version in the hub env to the same version in the user env
Reported in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/642
> Pin chardet

- docs/topic/requirements.rst
It looks like the link to the resource estimation page was not showing in:
https://tljh.jupyter.org/en/latest/topic/requirements.html?#cpu-memory-disk-space
> Fix link to resource estimation in server requirements docs

- docs/install/custom-server.rst
Fix the install instructions for own server setup where it said that 
the password was set in step 2 instead of 3.
> Own server install sets admin password in step 3

- dev-requirements.txt
- tljh/installer.py
We still need to pin chardet because the aiohttp latest version still has a requirement of chardet<4.
Let's wait until a new aiohttp release before removing our version pins
> Pin chardet again and pin it for tests also.

- integration-tests/test_extensions.py
- tljh/installer.py
- tljh/requirements-base.txt
JupyterLab 3.0 no longer equires npm to build extensions!
This should hopefully let us reduce the memory requiremets
for TLJH.
> Upgrade to JupyterLab 3.0

- tljh/installer.py
The currently pinned dependency "jupyterhub-nativeauthenticator==0.0.5" hast a critical and hard to detect bug.
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/631
Maintainer recommends to update to `0.0.7`.
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/631#issuecomment-826073460
> bump nativeauthenticator version to avoid critical bug

- .pre-commit-config.yaml
I've applied all but the black autoformatting changes for this pre-commit-config in #747. The config contains typical pre-commit hooks as found in jupyterhub, kubespawner, and other repos.
> Add .pre-commit-config

- .circleci/config.yml
- docs/index.rst
- docs/topic/installer-actions.rst
- tests/test_conda.py
- tljh/installer.py
- tljh/traefik.py
Fixes [https://github.com/jupyterhub/the-littlest-jupyterhub/issues/62#](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/62#)
Fixes #727 
- [X ] Add / update documentation
-  This PR shouldn't change anything from the user's point of view, but I added a couple of lines to state explicitly that this supports ARM 64 and AMD64 architectures and that it uses a miniforge conda environment.
- [ X] Add tests
- Updated ``tests/test_conda.py`` to use the miniforge installer instead of miniconda.
> Add support for installing TLJH on Arm64 systems

- docs/contributing/plugins.rst
I had wasted some time figuring out how to use some of the plugin hooks, before realizing that this repo's _integration-tests_ repo had implementations of each one. Updated the documentation in the hope of potentially saving time for future users.
> updating 'plugin' documentation

- docs/topic/tljh-config.rst
The current example (https://tljh.jupyter.org/en/latest/topic/tljh-config.html#advanced-config-yaml) doesn't show `unset`
> DOC: update sudo tljh-config --help demo

- docs/topic/customizing-installer.rst
I'll confess I didn't find this section until I came across https://github.com/jupyterhub/the-littlest-jupyterhub/pull/551
This PR moves the link higher up in the section to get more visibility. It also gives more context about what is on that page.
I also made a note that `git+https://github.com/yuvipanda/tljh-pangeo@v0.1` doesn't exist as I may not be the only person to copy and paste and get an error.
> DOC: move link to contributing/plugin higher

- .github/workflows/integration-test.yaml
`$GITHUB_ENV` has no effect until the next step, so without this `echo $BOOTSTRAP_PIP_SPEC` is always empty
> github workflow: echo $BOOTSTRAP_PIP_SPEC

- bootstrap/bootstrap.py
Using `HEAD` for https://raw.githubusercontent.com/ doesn't seem to be working and https://raw.githubusercontent.com/jupyterhub/jupyterhub/HEAD/share/jupyterhub/static/favicon.ico throws a 404
-<s>[ ] Add / update documentation</s>
-<s>[ ] Add tests<s>
> Update progress_page_favicon_url link

- docs/topic/idle-culler.rst
JupyterHub does not poll servers, servers post activity
> clarify direction of information in idle-culler

- .github/dependabot.yml
- .github/workflows/integration-test.yaml
- .github/workflows/unit-test.yaml
- ci: add dependabot bumping of github actions
- ci: update github action versions
> ci: add dependabot for github actions and bump them now

- .github/workflows/integration-test.yaml
- Addresses https://github.com/jupyterhub/team-compass/issues/579 for this repo.
I confirmed that the test failures in this PR are unrelated as they [occurr in the main branch](https://github.com/jupyterhub/the-littlest-jupyterhub/actions/runs/3461480274) as well now. See https://github.com/jupyterhub/the-littlest-jupyterhub/issues/830 about that.
> ci: fix deprecation of set-output in github workflows

- tljh/installer.py
- tljh/requirements-base.txt
Fixes #846
Tested by rerunning installer in dev setup
```
source /opt/tljh/hub/bin/activate
cd /srv/src
python3 -m tljh.installer
```
> Ensure SQLAlchemy 1.x used for hub

- .github/integration-test.py
- docs/requirements.txt
- integration-tests/test_install.py
Fix broken CI
This includes the debug PR from @manics #839 and fixes the supplemetal group issue and broken rtd build.
There appears to be some flakiness with integration tests still but have a green build triggered by an empty commit..
Fixes #830
> Fix broken CI

- integration-tests/test_hub.py
- tljh/installer.py
- tljh/requirements-base.txt
Should upgrade base python version separately
> update: jupyterhub 3, oauthenticator 15, systemdspawner 0.17 (user env: ipywidgets 8)

- tljh/log.py
init_logging is called many times in test_config, which has been registering numerous duplicate log handlers, attached to stderr that's closed between tests
> avoid registering duplicate log handlers

- docs/contributing/docs.md
- docs/contributing/packages.md
- docs/topic/tljh-config.md
- integration-tests/test_extensions.py
- tests/test_configurer.py
- tljh/configurer.py
- tljh/requirements-base.txt
As a followup to https://github.com/jupyterhub/the-littlest-jupyterhub/pull/842/files#r1146062727 in where we concluded that nteract-on-jupyter was deprecated (https://github.com/nteract/nteract/issues/5554#issuecomment-852434391).
> breaking, maint: remove deprecated nteract-on-jupyter

- .circleci/config.yml
- .github/integration-test.py
- .github/workflows/integration-test.yaml
- .github/workflows/unit-test.yaml
- README.md
- bootstrap/bootstrap.py
- dev-requirements.txt
- Closes #868 
@minrk with this merged, I figure we should re-run tests in #858 as well, which I then think should be merged if it passes.
> maint: add upgrade test from main branch, latest release, and 0.2.0

- docs/topic/idle-culler.md
- tests/test_configurer.py
- tljh/configurer.py
This is a duplicate of #855 by @stevejpurves that has been manually rebased to handle conflicts following from rST to MyST. I had to open a new PR to resolve this as I wasn't allowed to push to #855
@stevejpurves is this okay with you to merge? I made one edit besides the rST -> MyST markdown conversions required to solve merge conflicts from #863. You can see that change in a comment below.
Closes #855.
If you are using TLJH with named servers, it can be a requirement that the server is removed when culled. This PR is to expose the underlying IdleCuller option, allowing it to be set via `tljh-config`.
> added `remove_named_servers` setting for jupyterhub-idle-culler

- docs/howto/auth/awscognito.md
This is a recreation of https://github.com/jupyterhub/the-littlest-jupyterhub/pull/854, rebasing the PR having merge conflicts to add documentation in MyST markdown instead of the original change that was in .rst format.
Original commit message:
> After struggling with my custom department claim and getting helped in https://discourse.jupyter.org/t/genericauthenticator-with-cognito-how-to-check-for-department-match/18105/1 I wanted to give back to the community.
- Closes #854
---
@nodomain I hope this is okay with you, I want to push towards a new release and want your contribution merged for the changelog I'm writing.
> docs(awscognito): add custom claims example

- .github/workflows/unit-test.yaml
- bootstrap/bootstrap.py
When the bootstrap script runs, we are upgrading pip in the hub env. Let's upgrade to pip `23.1.*` by default, up from `21.3.*`.
- Closes #889
> Upgrade pip in hub env from 21.3 to to 23.1 when bootstrap script runs

- docs/conf.py
This fixes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/565
Interestingly pydata-sphinx-theme turns this on by default.
> docs: disable navigation with arrow keys

- integration-tests/conftest.py
- integration-tests/test_bootstrap.py
- integration-tests/test_proxy.py
- setup.py
- tests/test_configurer.py
- tests/test_traefik.py
- tljh/config.py
- tljh/configurer.py
- tljh/jupyterhub_config.py
- tljh/traefik-dynamic.toml.tpl
- tljh/traefik.py
- tljh/traefik.toml.tpl
Updates:
- jupyterhub-traefik-proxy to 1.0
- traefik to 2.10
traefik v2 totally changed their config file format, so several config options needed to move around, but ultimately the behavior is unchanged. jupyterhub-traefik-proxy 1.0 is required to use traefik v2 due to the config and API changes. Some configuration is no longer required as jupyterhub-traefik-proxy writes initial dynamic config (api route, auth) during its startup, instead of requiring to duplicate that info to the traefik config file.
This is a breaking change for the rare cases where users configured traefik or TraefikProxy directly, since both are major changes, but for most users the change should not be noticed (🤞) except as a performance boost when there are many users.
closes #513
> Traefik v2, TraefikProxy v1

- docs/howto/auth/google.md
- docs/topic/tljh-config.md
My institution uses TLJH on Google Cloud and uses Google Workspace for auth, specifically Google Groups. 
This PR fills out some of the TLJH Google auth docs and makes some small changes to a linked page.
> Update Google auth docs

- tljh/requirements-hub-env.txt
- jupyterhub-tmpauthenticator is bumped from 0.6 to 1.0.0 and has breaking changes for users of it outlined [in the changelog](https://github.com/jupyterhub/tmpauthenticator/blob/main/CHANGELOG.md)
- jupyterhub-nativeauthenticator is bumped from 1.1.0 to 1.2.0 and comes with jupyterhub 4 support
- jupyterhub-configurator is bumped from 317759e to 996405d and comes with some button feedback
> Update nativeauthenticator, tmpauthenticator, and jupyterhub-configurator

- docs/topic/tljh-config.md
- tests/test_traefik.py
- tljh/config.py
- tljh/configurer.py
- tljh/traefik.toml.tpl
This PR allows using `http.address` and `https.address` to set the addresses that TLJH will listen on,
which is an empty address by default (it means it listens on all interfaces by default, as it is the current behavior).
Tested and documented also!
Close #903
> Add a Traefik configuration to listen on a specific address (#903)

- tljh/requirements-hub-env.txt
- tljh/user_creating_spawner.py
The breaking changes in SystemdSpawner are listed as:
>- Systemd v243+ is now required, and v245+ is recommended. Systemd v245 is available in for example Ubuntu 20.04+, Debian 11+, and Rocky/CentOS 9+.
>- Python 3.8+, JupyterHub 2.3.0+, and Tornado 5.1+ is now required.
>- `SystemdSpawner.disable_user_sudo` (influences systemd's `NoNewPrivileges`) now defaults to `True`, making the installation more secure by default.
I think only the `disable_user_sudo=True` as default change is the only possibly breaking change. I've added a commit to make admin users get it set to False and non-admin users get it set to True explicitly in TLJH now. This leads to the following breaking change:
If a non-admin jupyterhub user has been granted sudo permissions, without being granted jupyterhub admin …
> Update systemdspawner from version 0.17.* to >=1.0.1,<2

- .github/workflows/integration-test.yaml
We have a odd test, the integration-tests/test_bootstrap.py, that is different from the other integration tests. It can be refactored further and made like the others I think, but for now, let's not run it in sequence with the other tests, but isolate it.
Isolating it makes us not run it for each supported linux distribution for now, but we reduce test duration by ~3 minutes or so.
Another key benefit of separating this is that its easier to understand that test_bootstrap.py currently is quite different from the other integration tests, and has different needs etc, allowing future refactoring and general maintenance easier.
> test refactor: put bootstrap tests in an isolated job, save ~3 min in each of the integration test jobs

- tljh/conda.py
- tljh/installer.py
an old conda bug causes RemoveError: requests is a dependency of conda when installing other packages (closes #918).
<del>
Upgrading conda itself first avoids this bug (we _may_ want `--force` here, which some folks have seen required when conda itself is messed up, but let's avoid it for now). So we know that the version in 0.2.0 (4.10) is not actually new enough to work. It's unclear what the true minimum version is to fix this, but the important thing is that it will be upgraded if it's still the version in 0.2.0 (4.10), so pick the versions from today which we know works, and will be the version upgraded-to if an 0.2 install has yet to update conda.
</del>
`conda install --force-reinstall conda` is the fix for this, because `conda install conda` will fail to upgrade if we're in this …
> --force-reinstall old conda to ensure it's working before we try to install conda packages

- tests/test_installer.py
I was considering if we could get even newer versions of mamba for example, but we can only bump based on mambaforge releases that bundle with python/conda/mamba. I added a comment to clarify this a bit, and sorted some dicts for consistency.
> test refactor: add comment about python/conda/mamba

- docs/howto/auth/awscognito.md
- docs/howto/auth/dummy.md
- docs/howto/auth/firstuse.md
- docs/howto/auth/github.md
- docs/howto/auth/google.md
- docs/howto/auth/nativeauth.md
- tljh/requirements-hub-env.txt
While I think it would be good if we could update all the authentication documentation, I don't think we should try get that done before a release. So instead of doing that, I made disclaimers to the documentation we had, suggesting that for example the OAuthenticator project's documentation should be used pirmarily and the tljh provided docs should be used as a complement only.
This is a preview of the warning, and you can preview it in the read the docs PR build [here](https://the-littlest-jupyterhub--924.org.readthedocs.build/en/924/howto/auth/github.html):
> breaking: update oauthenticator from 15.1.0 to >=16.0.2,<17, make tljh auth docs link out

- integration-tests/test_extensions.py
- tljh/requirements-user-env-extras.txt
Update Jupyter Notebook, JupyterLab and Jupyter Resource Usage to the latest major releases:
> Update Notebook, JupyterLab, Jupyter Resource Usage

- docs/conf.py
- docs/howto/user-env/notebook-interfaces.md
- docs/reference/changelog.md
- tests/test_configurer.py
- tljh/configurer.py
This PR changes the default value for the TLJH config `user_environment.default_app` to `jupyterlab`, which makes `c.Spawner.default_url` be set to `/lab` by default in TLJH.
To revert to the behavior before this, a TLJH admin can do:
```
sudo tljh-config set user_environment.default_app classic
```
---
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/773
> Launch into `/lab` by default by changing TLJH config's default value

- docs/conf.py
- docs/howto/admin/upgrade-tljh.md
- docs/howto/index.md
- docs/howto/user-env/notebook-interfaces.md
- docs/reference/changelog.md
- docs/topic/index.md
- docs/topic/installer-upgrade-actions.md
- docs/topic/three-environments.md
- docs/troubleshooting/index.md
- tljh/requirements-hub-env.txt
This PR adds the final pieces of documentation that I think is relevant to cut a 1.0.0. I hope that we can get this merged today or tomorrow and that we can go for 1.0.0 tomorrow.
- two topic / explanation sections:
- one describing the system/hub/user environments ([preview](https://the-littlest-jupyterhub--932.org.readthedocs.build/en/932/topic/three-environments.html))
- one about whats done during upgrades ([preview](https://the-littlest-jupyterhub--932.org.readthedocs.build/en/932/topic/installer-upgrade-actions.html))
- one how-to section, how to make an upgrade ([preview](https://the-littlest-jupyterhub--932.org.readthedocs.build/en/932/howto/admin/upgrade-tljh.html))
I don't have time to iterate much on this and hope it can be seen as an incremenetal improvement having this as a …
> docs: add docs about environments and upgrades

- docs/howto/auth/nativeauth.md
The URL at the bottom of the page https://tljh.jupyter.org/en/latest/howto/auth/nativeauth.html does not show correctly. The syntax was not markdown -> the pull request simply fixes that.
> Fix URL syntax in nativeauth.md

- tljh/requirements-hub-env.txt
I think this is related to:
- #950
- #951 
- #954
> Add missing oauthenticator dependency for AzureADOAuthenticator

- docs/install/amazon.md
This PR adjusts the wording of a sentence in the [Installing on Amazon Web Services](https://tljh.jupyter.org/en/latest/install/amazon.html) page. I was initially going to just move the comma in the original sentence ("If you have, one from before you can select it and" --> "If you have one from before, you can select it and"), but then I thought the wording proposed in this PR is more clear.
If you prefer a different change, such as the comma relocation, I am happy to modify the PR.
Before:
After:
> Reword documentation sentence

- docs/install/amazon.md
This PR fixes a typo and replaces the word. The typo is of "distinguishing", but "distinctive" makes more sense to me in the context of the sentence it is in. Let me know if you prefer just fixing the typo and leaving "distinguishing".
Before (from [Installing on Amazon Web Services](https://tljh.jupyter.org/en/latest/install/amazon.html)):
After:
> Fix typo and replace word

- .github/integration-test.py
- integration-tests/plugins/simplest/tljh_simplest.py
- integration-tests/test_simplest_plugin.py
- tljh/installer.py
We have previously re-installed (without upgrading) conda and mamba, and done it based on specific versions. I think we are required to do this uncodntionally though. I think based https://github.com/conda/conda/issues/12366#issuecomment-1466144007 that since tljh make use of both pip and conda/mamba to install packages via plugins, even though we mostly use pip, we must do this re-install to ensure conda/mamba is functional before an tljh upgrade.
I think we end up with `requests` installed via pip during the initial setup of tljh, and that sets us up for issues when we are to make an upgrade later when conda/mamba is being used via plugins. I think the reason we didn't have this error before in tests, but do now, relates to new versions of `openssl` have been released, and that …
> Re-install conda/mamba for every tljh upgrade (doesn't imply upgrade)

- integration-tests/test_hub.py
Just something observed when trying to resolve #974, which is fixed by jupyterhub 4.1.5 release and work in #962 by @jrdnbradford.
> tests: fix to catch test failure earlier when they really happen

- docs/howto/admin/https.md
While trying to configure manual HTTPS for TLJH i found that details on how to had custom domain was missing, for easy understanding and clarity had to propose this change.
> Added missing details on how to add custom domain from manual HTTPS  configuration

- docs/howto/admin/systemd.md
- tljh/systemd-units/jupyterhub.service
-m jupyterhub.app results in multiple JupyterHub classes being defined and jupyterhub.app.JupyterHub never being instantiated
closes #987
> fix `-m` invocation of jupyterhub

- docs/topic/installer-actions.md
- tests/test_conda.py
- tests/test_installer.py
- tljh/installer.py
mambaforge-named installers are deprecated, as mamba has been in miniforge for some time now, so they will be merged. Mambaforge releases will stop later this year.
> Update base user environment to miniforge 24.7.1-0 (Python 3.12)

- dev-requirements.txt
- integration-tests/requirements.txt
- setup.py
- tljh/config.py
- tljh/requirements-hub-env.txt
- makes filelock a dependency of tljh (missing this is the reason for the in-function imports)
- adds config_file_lock context manager to re-use
- moves filelock import to module level
- fixes exit codes, stderr messages
small polish on #976
> consolidate lock file handling

- .github/workflows/integration-test.yaml
- .github/workflows/unit-test.yaml
I think https://github.com/jupyterhub/the-littlest-jupyterhub/actions/runs/10964462847/job/30448138728 failed due to caching issues. I want to reduce complexity by not using cache when we not only configure runs-on but also container. Debugging failures in this complicated CI system is hard, needing to first rule out its about cache issues makes it even harder, so I'd rather let it take a few more seconds.
> ci: cache pip only when no container is used

- tljh/installer.py
Just wanted to have the most recent stuff before release, changelogs indicate this release is probably irrelevant to update for tljh though.
> Update to install miniforge 24.7.1-2 from 24.7.1-0

- tljh/requirements-user-env-extras.txt
By declaring these lower bounds, it becomes a bit easier to help others
using tljh, because we can know that fresh installations of tljh should
have at least these versions of software etc.
> Bump the requirements-user-env-extras.txt lower version bounds

- tljh/installer.py
- tljh/traefik.py
The traefik binary gets re-installed if there is a version mismatch of whats available and whats desired - nice!
I don't see anything breaking in the traefik changelog related to our static and dynamic config - nice!!
I don't think this is to be considered a breaking change.
> Update traefik from 2.10.1 to 3.1.4

- .github/workflows/integration-test.yaml
Currently covered by `latest`, but won't be when 2.0.0 is released
> Test upgrade from 1.*

- docs/reference/changelog.md
- for #991
---
Is there something else to include before going for a 2.0.0b1 release?
---
I've recently self-merged these and included them in this changelog.
- #1001
- #1002
---
Link to rendered changelog: https://the-littlest-jupyterhub--1000.org.readthedocs.build/en/1000/reference/changelog.html
I've not done work including v1 -> v2 upgrade instructions. My take is that its relevant to do when there is a distribution specific migration that needs to be done for example, but I think that isn't the case for this major version of tljh, so I've leaned on referencing other software's changelogs.
> Add changelog for 2.0.0b1

- tljh/requirements-hub-env.txt
I'm not sure why we have tests failing in main now.
The only change made was #1004 which I merged without waiting for tests to go green as I reasoned they couldn't be impacted by the change, and I don't think they were but that the tests went red because of something else, such as jupyterhub 5.2.0 being released?
> hub env: pin to jupyterhub 5.1.0

- tljh/requirements-hub-env.txt
I think this may fix some issues for people, its something we do for z2jh's images for example.
> hub env: avoid installing pycurl using wheel with an issue

- tljh/requirements-hub-env.txt
- systemdspawner is not erroring on tests with JupyterHub 5.2.0 ([test run](https://github.com/jupyterhub/systemdspawner/actions/runs/11424844766/job/31785717454))
- hubtraf is not erroring on tests with JupyterHub 5.2.0 ([test run](https://github.com/yuvipanda/hubtraf/actions/runs/11424939017/job/31785956321?pr=49))
- tljh is erroring on tests with JupyterHub 5.2.0 though
It seems that starting the server leads to 500 error:
```
Debug: server-start fc621e8f6e9ca691 resp:<ClientResponse(http://localhost/hub/spawn) [500 Internal Server Error]>
```
```
Oct 20 08:35:05 9ce0cc64b132 python3[3068]: [I 2024-10-20 08:35:05.595 JupyterHub log:192] 302 POST /hub/login -> /hub/spawn (fc621e8f6e9ca691@127.0.0.1) 28.60ms
Oct 20 08:35:05 9ce0cc64b132 python3[3068]: [I 2024-10-20 08:35:05.621 …
```
> Update jupyterhub pinning to >=5.2.0,<6 from ==5.1.0

- README.md
- docs/index.md
We have a mention about TLJH being in a beta state, I think its better to not mention its development state now that we are making major releases with changelogs etc.
> Remove mention about beta state

- docs/topic/tljh-config.md
- tests/test_config.py
- tljh/config.py
- tljh/config_schema.py
Fixes #1012. 
The config schema for `cpu` limits now accepts values such as `3`, `3.5` and `"None"`. Added `minimum`s of `0` to prevent negative numerics.
Details on `number` can be found in the [JSON Schema docs](https://json-schema.org/understanding-json-schema/reference/numeric).
> Fix `cpu` and `memory` config validation in JSON schema

- docs/contributing/dev-setup.md
- integration-tests/Dockerfile
Without this, the current dev setup documentation does not work.
> Set development env vars in dev documentation correctly

- README.md
It's out of date, as reported in https://discourse.jupyter.org/t/installation-of-tljh-on-ubuntu-20-04-does-not-work/32823
> Fix Ubuntu version in README

- integration-tests/test_extensions.py
Fix for integration test failures that seem to have started somewhat recently. See failures in #1024 and several recent `pre-commit autoupdate`s: https://github.com/jupyterhub/the-littlest-jupyterhub/actions/workflows/integration-test.yaml. 
Edit: see successful tests in my own fork: https://github.com/jrdnbradford/the-littlest-jupyterhub/actions/runs/13729823550
> Fix `test_serverextensions` integration test

- docs/topic/idle-culler.md
These are the settings in `values.yaml`:
```
cull:
enabled: true
users: false # --cull-users
adminUsers: true # --cull-admin-users
removeNamedServers: false # --remove-named-servers
timeout: 3600 # --timeout
every: 600 # --cull-every
concurrency: 10 # --concurrency
maxAge: 0 # --max-age
```
> Fix default settings for culler instructions

- tljh/requirements-hub-env.txt
Use of `--no-binary` was required for `pycurl` `7.45.3` due to a wheel problem. Related issues:
- https://github.com/jupyterhub/oauthenticator/issues/731
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/964
- https://github.com/pycurl/pycurl/issues/834
As of `7.45.4` this was corrected, installing the latest `pycurl` from the wheel now works. This saves a non-negligible amount of time in CI actions, tests, and installation.
> Use `pycurl` `.whl` for hub environment
