- docs/guides/notebook-interfaces.rst
> Pour some tea 🍵

- docs/tutorials/jetstream.rst
Many minor issues --
* JetStream -> Jetstream
* minor spelling fixes/typos
* link directly to Jetstream portal
* note that users are added to UNIX upon first login.
Ready for review & merge!
> [MRG] update jetstream tutorial with links, minor fixes

- docs/_static/custom.css
- docs/_static/custom.js
- docs/conf.py
- docs/guides/admin.rst
- docs/guides/install.rst
- docs/guides/notebook-interfaces.rst
- docs/index.rst
- docs/troubleshooting/logs.rst
- docs/tutorials/add_packages.txt
- docs/tutorials/add_users.txt
- docs/tutorials/digitalocean.rst
- docs/tutorials/google.rst
- docs/tutorials/jetstream.rst
This makes small edits to some text as I was going through the instructions (primarily the gcloud ones)
It also implements some simple javascript/CSS that creates copy buttons to the right of each code block. For an example of what this looks like in action, see:
http://predictablynoisy.com/the-littlest-jupyterhub/
> Small text improvements + adding copy buttons to text blocks

- tljh/installer.py
Here is my attempt at fixing a hard-coded constant and handling transient errors during the install phase.
My error handling code is hmmm... suboptimal (duplicates code), so any suggestion is welcome.
Fixes #30
> Handle transient errors

- docs/index.rst
> Fix link to custom tutorial

- docs/index.rst
- tests/test_conda.py
- tljh/conda.py
- tljh/installer.py
Also add docs about --admin option
Refer #49
> Add option to install requirements.txt file on install

- tljh/installer.py
> jupyterhub 0.9.1, notebook 5.6.0

- tljh/installer.py
> fix typo in installer

- docs/topic/customizing-installer.rst
Missed out adding file in previous commit
> Add doc on customizing installer

- README.rst
- bootstrap/bootstrap.py
- docs/topic/customizing-installer.rst
- docs/topic/security.rst
- docs/tutorials/custom.rst
- docs/tutorials/digitalocean.rst
- docs/tutorials/google.rst
- docs/tutorials/jetstream.rst
This lets me fork this repo without breaking everyone :)
> Replace pointers to yuvipanda/ on github with jupyterhub/

- README.rst
- docs/index.rst
Also add a date to when v0.1 is gonna hit
> Clarify development status warnings

- docs/contributing/dev-setup.rst
- docs/index.rst
- docs/topic/authenticator-configuration.rst
- docs/troubleshooting/logs.rst
> Add docs on using arbitrary authenticators

- bootstrap/bootstrap.py
- docs/troubleshooting/logs.rst
- tljh/apt.py
- tljh/conda.py
- tljh/installer.py
This enables debugging when a server does not come up as
expected.
Fixes #22
> Log bootstrap / installer messages to file as well

- docs/conf.py
> Customize theme to have better links in sidebar

- README.rst
- docs/index.rst
> Remove README note about HTTPS not being supported

- README.rst
> Fix quick links in README

- docs/topic/authenticator-configuration.rst
> Remove extreneous =

- .circleci/config.yml
- docs/Makefile
- docs/conf.py
- docs/contributing/docs.rst
- docs/howto/user-environment.rst
- docs/index.rst
- docs/install/custom-server.rst
- docs/topic/authenticator-configuration.rst
- docs/topic/security.rst
- docs/topic/whentouse.rst
This adds a CircleCI job that builds the documentation to make sure it builds. It also turns all warnings into errors. The changes to the docs are there to fix the warnings that are now errors.
> [MRG] Adding CI for documentation and fixing docs warnings

- integration-tests/test_extensions.py
- tljh/installer.py
> Install jupyterhub extension for jupyterlab

- docs/topic/tljh-config.rst
Updated topic/tljh-config.rst to include some of the property paths that are declared in the code base but not yet documented.
> Added existing property-path for tljh-config set method

- docs/install/custom-server.rst
> polish local server install

- docs/topic/whentouse.rst
> typo questoins -> questions.

- docs/topic/security.rst
> Remove extra space after opening paren

- docs/topic/security.rst
- integration-tests/test_hub.py
- tests/test_normalize.py
- tljh/jupyterhub_config.py
- tljh/normalize.py
> Normalize systemuser

- docs/howto/auth/dummy.rst
just a small typo to make the code formatting render properly. @yuvipanda I'm gonna merge this tomorrow AM if it hasn't been done before then in order to make sure it looks good for the talk :-)
> small typo in docs

- tljh/installer.py
Reverts https://github.com/jupyterhub/the-littlest-jupyterhub/pull/138 and
fixes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/236.
> Update nodejs to 10.x LTS

- tljh/installer.py
- tljh/migrator.py
> Use tljh logger in installer

- integration-tests/test_extensions.py
- tljh/installer.py
Most people expect the base notebook experience to include
working ipywidgets
> Add ipywidgets to base installation

- bootstrap/bootstrap.py
Some servers don't have git on by default
> Install git explicitly during bootstrap

- docs/howto/auth/github.rst
> fix GitHub login config missing callback URL

- docs/contributing/docs.rst
ask and ye shall receive @yuvipanda
> updating the image size text

- setup.py
- tljh/configurer.py
- tljh/jupyterhub_config.py
consolidate to a single yaml implementation, removing pyyaml
> single yaml implementation

- docs/contributing/dev-setup.rst
- Dockerfile moved to integration-tests
- remove sudo from commands (usually not needed, better added by users where it is)
> update dev-setup commands

- docs/howto/auth/nativeauth.rst
- docs/index.rst
- docs/topic/authenticator-configuration.rst
- tests/test_configurer.py
- tljh/installer.py
> Add NativeAuth as an optional authenticator

- integration-tests/test_extensions.py
- tljh/installer.py
Security patch - https://blog.jupyter.org/open-redirect-vulnerability-in-jupyter-jupyterhub-adf43583f1e4
> Bump jupyterhub version

- docs/topic/installer-actions.rst
> typo fix in installer actions

- tljh/installer.py
JupyterHub upgrade provides a security fix, and systemdspawner
upgrade provides bug fixes.
> Bump JupyterHub and systemdspawner versions

- README.rst
I didn't reword too much, but the second occurrence of "environment" could be merged as well.
> Remove repeated sentence from README.rst

- setup.py
- tljh/traefik.py
> Retry downloading traefik if it fails

- docs/install/custom-server.rst
- Use sudo when installing packages
- Minor text cleanup
> Minor cleanup of custom server install documents

- docs/howto/content/share-data.rst
- docs/topic/authenticator-configuration.rst
> Remove stray = in authenticator configuration example

- docs/topic/installer-actions.rst
> Fix typo: cohnfig -> config

- docs/contributing/docs.rst
A little improvement to the docs to get all the Sphinx dependencies installed locally.
> Clarify the steps to build the docs locally

- docs/topic/customizing-installer.rst
> Minor typo fix: praticular -> particular

- docs/howto/admin/https.rst
> Typo fix: `s` -> `is`

- tljh/apt.py
It seems to be blocking waiting on user input
for a couple packages now
Fixes #379
> Tell apt-get to never ask questions

- docs/topic/tljh-config.rst
> Add port configuration to docs

- docs/install/amazon.rst
> fixing typo (remove "can add rules") in amazon.rst

- docs/install/amazon.rst
> fixed typo in key pair section

- tljh/traefik.py
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/441
> Upgrade traefik version

- tljh/apt.py
Should fix https://github.com/jupyterhub/the-littlest-jupyterhub/issues/445
> Write out deb line only if it already doesn't exist

- docs/install/azure.rst
This PR adds a note on the existence of the new  Deploy to Azure button (discussion from #388).
> [MRG] Azure docs - add details on the new Azure deploy button

- docs/howto/auth/awscognito.rst
- docs/howto/index.rst
> Added AWS Cognito docs

- integration-tests/plugins/simplest/tljh_simplest.py
- integration-tests/test_simplest_plugin.py
- tljh/hooks.py
- tljh/jupyterhub_config.py
- tljh/user.py
- tljh/utils.py
So I plugged the hook into ensure_user, which works locally. I did not yet write a test, because I am unsure about where would be the best location to test this functionality (and I did not want to break any existing test). Maybe you could point this out to me. 
I think adding documentation would not be needed, as the hooks are referenced as a python file in the docs.
(Closes #451 )
> Add hook for new users

- docs/topic/installer-actions.rst
- docs/troubleshooting/logs.rst
> Remove configurable-http-proxy references from docs #494

- README.rst
There might not be an official number of users, but this changes makes it the same as in the repo description and in the docs.
> Use the same 1-100 numbers as in the docs and repo description

- tljh/installer.py
This change updates the base hub packages to their latest stable version on PyPI.
> Update hub packages to the latest stable versions

- docs/install/amazon.rst
> Fixes 'availabe' > 'available' spelling in docs

- docs/topic/customizing-installer.rst
Add some documentation to install multiple plugins with the TLJH installer, as well as a link to the TLJH Plugins page.
> Add documentation to install multiple plugins

- integration-tests/test_admin_installer.py
- integration-tests/test_hub.py
Update the tests to keep up with the great things happening in [hubtraf](https://github.com/yuvipanda/hubtraf/tree/master/hubtraf) (:heart:  @yuvipanda )
> ensure_server is now ensure_server_simulate

- integration-tests/test_extensions.py
- tljh/installer.py
- tljh/requirements-base.txt
2.x has been around for a while
> Upgrade JupyterLab version

- tljh/installer.py
New version released, with https://github.com/jupyterhub/systemdspawner/pull/53
> Bump systemdspawner

- bootstrap/bootstrap.py
The <html> tag was not correctly closed with a </html> tag.
> Fix HTML of bootstrap

- tljh/jupyterhub_config.py
- tljh/user_creating_spawner.py
Fixes #619 
This is only a minor change for the project, which has no direct impact on the functionality. However, it would make my life a bit easier, resulting in less code duplication in my own TLJH setup (see description of issue #619). Also, it would be a *cleaner* solution in general, separating class implementations and configuration scripts.
> proposed changes for issue #619

- integration-tests/test_extensions.py
- tljh/requirements-base.txt
> Bump a few of the dependencies

- tljh/requirements-base.txt
Bug and solution first reported here: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/645
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/645
> Revert and pin notebook version

- docs/howto/auth/firstuse.rst
For this page: https://tljh.jupyter.org/en/latest/howto/auth/firstuse.html#enabling-the-authenticator
> Fix code formatting in the docs

- setup.py
- tljh/installer.py
The new traefik-proxy version shouldn't cause conflicts with other pkgs anymore
> Bump traefik-proxy version and remove pin.

- docs/contributing/packages.rst
- docs/howto/admin/nbresuse.rst
- docs/howto/admin/resize.rst
- docs/howto/admin/resource-estimation.rst
- docs/topic/installer-actions.rst
- integration-tests/test_extensions.py
- tests/test_installer.py
- tljh/installer.py
- tljh/requirements-base.txt
Replaces #647 with the suggested changes.
> Upgrade to Jupyterlab 3.0 and Jupyter Resource Usage

- docs/install/amazon.rst
> Note smallest AWS instance TLJH can run on

- .circleci/config.yml
- .github/workflows/unit-test.yaml
Ref:  https://github.com/jupyterhub/the-littlest-jupyterhub/issues/659
> Switch unit tests from CircleCI to GitHub actions

- tljh/jupyterhub_configurator_config.py
Forgot to add the configurator config :disappointed_relieved:
> Add missing configurator config

- docs/topic/tljh-config.rst
Added examples to "Users Lists" section to help add users or remove users from any list.
> Add "Users Lists" example

- tljh/installer.py
- tljh/requirements-base.txt
Fixes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/685
> Bump hub and notebook versions

- .pre-commit-config.yaml
- tljh/requirements-base.txt
I mistakenly added requirements-txt-fixer which has turned out to cause problems, which is in this PR documented in the relevant requirements.txt file to help figuring out why that is in more detail at some later time.
> pre-commit: remove requirements-txt-fixer

- docs/install/amazon.rst
Closes https://github.com/jupyterhub/the-littlest-jupyterhub/issues/770
I opted not to update the screen shot but I can do if required.
> DOC: update info on AWS get system log

- docs/install/add_packages.txt
> DOC: hyperlink there

- docs/contributing/plugins.rst
Found this on pypi https://pypi.org/search/?q=tljh&o=
> DOC: add tljh-db plugin to list

- bootstrap/bootstrap.py
Adding this as I need to check i'm passing the environment variable correctly
> extra logger.info

- tljh/installer.py
> ENH: add logging if user-requirements-txt-url found

- tljh/installer.py
https://github.com/jupyterhub/systemdspawner/pull/94 just made
a release
- <s>[ ] Add / update documentation</s>
- <s>[ ] Add tests</s>
> Bump systemdspawner version

- docs/topic/customizing-installer.rst
close https://github.com/jupyterhub/the-littlest-jupyterhub/issues/827
> Fix typo with --show-progress-page argument in example

- docs/howto/env/user-environment.rst
> Typo in user-environment.rst

- setup.py
ahead of various upgrades that have been in the works for some time
> bump version to 1.0.0.dev0

- docs/contributing/dev-setup.md
- docs/howto/admin/https.md
- docs/howto/auth/awscognito.md
- docs/howto/auth/github.md
- docs/howto/providers/azure.md
- docs/topic/tljh-config.md
I found a few more manual fixes needed for #863.
> docs: fix remaining issues following rst to myst transition

- .github/integration-test.py
- integration-tests/test_hub.py
make sure the hub has the version we expect
I think #885 is caused by jupyterhub 4, but I don't yet understand how/why we are getting that
> add integration test for hub version

- integration-tests/test_hub.py
- tljh/installer.py
- tljh/requirements-base.txt
- Followup to #842
The test failure is unrelated to this PR, but we should solve that in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/885 before merging this PR.
> update: jupyterhub 4

- tljh/requirements-hub-env.txt
I made a typo in #890, is that what has caused the tests to start failing? Yes!!!
- Closes #913
> Fix recently introduced failure to upper bound systemdspawner

- docs/reference/changelog.md
- tljh/requirements-hub-env.txt
> Update changelog for 1.0.0 release

- docs/howto/auth/github.md
- integration-tests/test_hub.py
- tljh/configurer.py
- tljh/requirements-hub-env.txt
require 5.1.0 for security fixes
> jupyterhub 5

- dev-requirements.txt
- integration-tests/requirements.txt
- tljh/config.py
- tljh/requirements-hub-env.txt
This adds a lockfile for the TLJH config. Given the reused code it seems things are due for a refactor. I partially did this by abstracting the code that retrieves the current config.
> Add TLJH config lockfile

- docs/howto/auth/awscognito.md
- tljh/requirements-hub-env.txt
azuread no longer has its own dependencies
#991
> update oauthenticator to 17

- docs/reference/changelog.md
- closes #991
I think we are ready to go at this point, shall we? The date should be updated before merge if we merge sometime beside monday oct 21.
> Add changelog for 2.0.0
